actionbar-format: "<color:#e02b2e><b>Combate</b><gray>:</gray></color> <color:#e02b2e><statuscombat>    <color:#e02b2e><b>Vidas</b><gray>:</gray></color> <color:#e02b2e><3>"
pvp-enabled-message: "<green>Activado</green>"
pvp-disabled-message: "<red>Desactivado</red>"
death-message: "<color:#e02b2e><b><player></b></color> <color:white>Ha perdido una</color> <color:#e02b2e><b>Vida</b></color>"
out-of-lives-message: "\n\n<color:#e02b2e><b>              GAME OVER!</b>\n\n<color:#e02b2e><b> <player></b></color> <color:white>Ha perdido todas sus</color> <color:#e02b2e><b>Vidas</b></color>\n\n"
lost-life-title: "<color:#e02b2e><b>💔</b>"
lost-life-subtitle: "Perdiste una Vida"
out-of-lives-title: "<color:#e02b2e><b>GAME OVER!</b>"
out-of-lives-subtitle: "Has pedido todas tus Vidas!"
bossbar-message: "<color:#e02b2e>Tiempo Restante<gray>:</gray> <color:white>{hours}<color:#e02b2e>H</color> <color:white>{minutes}<color:#e02b2e>M</color> <color:white>{seconds}<color:#e02b2e>S</color></color>"
pvp-enabled: "<green>El PvP ha sido activado!</green>"
pvp-disabled: "<red>El PvP ha sido desactivado!</red>"